# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    if: github.repository_owner == 'nurzhanme'
    name: Build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout Code
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v2

      - name: Set Release Version
        run: |
          [ ! -f semver ] && echo none > semver
          echo ::set-env name=RELEASE_VERSION::$(cat semver)
        shell: bash

      - name: Publish to NuGet
        if: env.RELEASE_VERSION != 'none'
        shell: bash
        run: |
          node packages/nurzhanme.Basisregisters.Build.Pipeline/Content/ci-nuget.js dist/$LIBNAME/$LIBNAME.$SEMVER.nupkg
        env:
          LIBNAME: AspNetCore.CustomHeaderMiddleware
          SEMVER: ${{ env.RELEASE_VERSION }}
          NUGET_HOST: ${{ secrets.NUGET_HOST }}
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

